### PR TITLE
Pin versions for pyproj and xyzservices

### PR DESCRIPTION
**Pull request by peanutfun**
Pin versions for pyproj and xyzservices and remove version pin for proj.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~~[ ] Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peanutfun** [comment]
@conda-forge-admin, please rerender

**Comment by peanutfun** [comment]
@emanuel-schmid Could you give the changes to `meta.yml` a quick look? https://github.com/conda-forge/climada-feedstock/pull/9/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a

**Comment by emanuel-schmid** [comment]
Cool. Thanks. Let's try it. There are a few package versions that would be updated in a new release but it doesn't matter here.

xyzservice will work, no doubt. But whether pyproj works better then proj - ? we shall see 😄

**Comment by peanutfun** [comment]
@emanuel-schmid Thanks for the feedback. Let's give it a try!

**Comment by peanutfun** [comment]
There seems to be a problem with access to the Climada Data API. I tried again, it's still there.

**Pull request merged**
